### ISSUE TITLE
opecv-python

### ISSUE THREAD

**Issue by knoppmyth** [linxiaohui/deepface_cv2#1]
Hi,

I tried to pip install deepface-cv2 but encountered an error:
`ERROR: Could not find a version that satisfies the requirement opecv-python (from deepface-cv2) (from versions: none)
ERROR: No matching distribution found for opecv-python`
Looks like you have a typo.

**Comment by linxiaohui** [comment]
thank you for comments.
fixed already

**Comment by Blaffy9090** [comment]
Same error
tried pip install deepface-cv2

INFO: pip is looking at multiple versions of deepface-cv2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement opecv-python (from deepface-cv2) (from versions: none)
ERROR: No matching distribution found for opecv-python

did you update released to pip version of the project?

**Comment by linxiaohui** [comment]
@Blaffy9090 fixed in the new version. sorry for the inconvenient
